#'  \code{pretty_var_names}
#'
#'  Makes variable names for publication
#'
#'  @param vars integer vector of which variable names to return
#'
#'  @return character vector
#'
#'  @export
#'
pretty_var_names <- function(vars)
{
  vn1 <- c(
    `(Intercept)` = "Intercept",
    v08 = "Voting in 2008",
    v10 = "Voting in 2010",
    v12 = "Voting in 2010",
    vote = "Voting (yes/no)",
    v08int = "Voting Intent (August 2008)",
    v10int = "Voting Intent (August 2010)",
    v12int = "Voting Intent (August 2012)",
    vint = "Voting Intent (August)",
    vint.rec = "Voting Intent (Recoded)",
    vint.miss = "Voting Intent (Missings)",
    Female = "Female",
    Race_white = "Race: White",
    Race_black = "Race: Black",
    Race_hisp = "Race: Hispanic",
    SchYear = "School Year (1-4)",
    NewScholar = "New Student",
    Rep = "Party ID: Republican",
    Dem = "Party ID: Democrat",
    Ind = "Party ID: Independent",
    Ideology = "Ideology (Conservative-Liberal)",
    Ideo_strength = "Ideology strength (Moderate-Extreme)",
    Interest_pol = "Political Interest",
    PolKn_tot = "Political Knowledge",
    PolitPref = "Party ID",
    Voted_08_mom = "Mother voted '08",
    Voted_12_mom = "Mother voted '12",
    Voted_08_dad = "Father voted '08",
    Voted_12_dad = "Father voted '12",
    v08m = "Mother voted '08",
    v12m = "Mother voted '12",
    v08d = "Father voted '08",
    v12d = "Father voted '12",
    PolitPref_mom = "Mother's party ID",
    PolitPref_dad = "Father's party ID",
    pprefm = "Mother's party ID",
    pprefd = "Father's party ID",
    Dem.m = "Democrat Mother",
    Dem.d = "Democrat Father",
    Rep.m = "Republican Mother",
    Rep.d = "Republican Father",
    Par.dd = "Democrat parents",
    Par.rr = "Republican parents",
    Par.rd = "Rep mother, Dem father",
    Par.dr = "Dem mother, Rep father",
    Par.drrd = "One Dem, one Rep parent",
    Obama_appr = "Approval of Pres. Obama",
    Chapter = "Chapter",
    ChapterN = "Chapter",
    `ChapterIllinois` = "Chapter.Illinois",
    `ChapterIndiana` = "Chapter.Indiana",
    `ChapterMarquette` = "Chapter.Marquette",
    `ChapterMiami` = "Chapter.Miami",
    `ChapterMichigan` = "Chapter.Michigan",
    `ChapterMichigan State` = "Chapter.MichiganState",
    `ChapterMinnesota` = "Chapter.Minnesota",
    `ChapterMissouri` = "Chapter.Missouri",
    `ChapterNorthern Illinois` = "Chapter.NorthernIllinois ",
    `ChapterNorthwestern` = "Chapter.Northwestern",
    `ChapterOhio State` = "Chapter.OhioState",
    `ChapterPurdue` = "Chapter.Purdue",
    `ChapterWisconsin` = "Chapter.Wisconsin"
  )
  vn2 <- c(
    ideomd.fr. = "Ideological divergence from friendship ties",
    ideosd0.fr. = "Ideological diversity among friendship ties",
    mvint.fr. = "Average friendship tie voting intent (August)",
    pvot.fr. = "Proportion of friendship ties who voted",
    in.deg.fr = "Popularity (number of friendship tie nominations)",
    ideomd.pol. = "Ideological divergence from political ties",
    ideosd0.pol. = "Ideological diversity among political ties",
    mvint.pol. = "Average political tie voting intent (August)",
    pvot.pol. = "Proportion of political ties who voted",
    in.deg.pol = "Popularity (number of political tie nominations)",
    ideomd.est. = "Ideological divergence from esteem ties",
    ideosd0.est. = "Ideological diversity among esteem ties",
    mvint.est. = "Average esteem tie voting intent (August)",
    pvot.est. = "Proportion of esteem ties who voted",
    in.deg.est = "Popularity (number of esteem tie nominations)",
    ideomd.est.out = "Ideological divergence from esteem ties",
    ideosd0.est.out = "Ideological diversity among esteem ties",
    mvint.est.out = "Average esteem tie voting intent (August)",
    pvot.est.out = "Proportion of esteem ties who voted",
    ideomd.time. = "Ideological divergence from time ties",
    ideosd0.time. = "Ideological diversity among time ties",
    mvint.time. = "Average time tie voting intent (August)",
    pvot.time. = "Proportion of time ties who voted",
    in.deg.time = "Popularity (number of time tie nominations)",
    ideomd.aca. = "Ideological divergence from academic ties",
    ideosd0.aca. = "Ideological diversity among academic ties",
    mvint.aca. = "Average academic tie voting intent (August)",
    pvot.ava. = "Proportion of academic ties who voted",
    in.deg.aca = "Popularity (number of academic tie nominations)",
    ideomd.no. = "Ideological divergence from negative ties",
    ideosd0.no. = "Ideological diversity among negative ties",
    mvint.no. = "Average negative tie voting intent (August)",
    pvot.no. = "Proportion of negative ties who voted",
    in.deg.no = "Popularity (number of negative tie nominations)",
    pvot2.fr. = "Proportion of friendship 2-step ties who voted",
    pvot2.pol. = "Proportion of Political 2-step ties who voted",
    pvot2.est. = "Proportion of Esteem 2-step ties who voted",
    pvot2.time. = "Proportion of Time 2-step ties who voted",
    pvotS.fr. = "Proportion of friendship co-partisan ties who voted",
    pvotD.fr. = "Proportion of friendship cross-party ties who voted",
    pvotS.pol. = "Proportion of Political co-partisan ties who voted",
    pvotD.pol. = "Proportion of Political cross-party ties who voted",
    mvintS.fr. = "Average friendship co-partisan tie voting intent",
    mvintD.fr. = "Average friendship cross-party tie voting intent",
    mvintS.pol. = "Average Political co-partisan tie voting intent",
    mvintD.pol. = "Average Political cross-party tie voting intent",
    pvot.fr.only. = "Proportion of friendship-only ties who voted",
    pvot.pol.only. = "Proportion of Political-only ties who voted",
    pvot.frandpol. = "Proportion of friendship AND political ties who voted",
    pvot.frorpol. = "Proportion of friendship OR political ties who voted",
    mvint.fr.only. = "Average friendship-only tie voting intent",
    mvint.pol.only. = "Average Political-only tie voting intent",
    mvint.frandpol. = "Average friendship AND political tie voting intent",
    mvint.frorpol. = "Average friendship OR political tie voting intent",
    party.hhi.fr. = "Concentration of party IDs among friend ties (HHI)",
    party.rhhi.fr. = "Fragmentation of party IDs among friend ties (1-HHI)",
    pdis.fr. = "Proportion of friend ties with different party ID",
    party.hhi.pol. = "Concentration of party IDs among political ties (HHI)",
    party.rhhi.pol. = "Fragmentation of party IDs among political ties (1-HHI)",
    pdis.pol. = "Proportion of political ties with different party ID",
    party.hhi.est. = "Concentration of party IDs among esteem ties (HHI)",
    party.rhhi.est. = "Fragmentation of party IDs among esteem ties (1-HHI)",
    pdis.est. = "Proportion of esteem ties with different party ID",
    party.hhi.time. = "Concentration of party IDs among time ties (HHI)",
    party.rhhi.time. = "Fragmentation of party IDs among time ties (1-HHI)",
    pdis.time. = "Proportion of time ties with different party ID",
    mpint.fr. = "Average friendship tie political interest",
    mpint.pol. = "Average political tie political interest",
    mpint.est. = "Average esteem tie political interest",
    mpint.time. = "Average time tie political interest",
    mpint.fr.only. = "Average friendship-only tie  political interest",
    mpint.pol.only. = "Average Political-only tie  political interest",
    mpint.frandpol. = "Average friendship AND political tie political interest",
    mpint.frorpol. = "Average friendship OR political tie  political interest",
    mpintS.fr. = "Average friendship co-partisan tie political interest",
    mpintD.fr. = "Average friendship cross-party tie political interest",
    mpintS.pol. = "Average Political co-partisan tie political interest",
    mpintD.pol. = "Average Political cross-party tie political interest",
    pvot.fpte. = "Proportion of total (f,p,t,e) ties who voted",
    pvot.fpt. = "Proportion of total (f,p, t) ties who voted",
    mvint.fpte. = "Average total (f,p,t,e) tie voting intent",
    mvint.fpt. = "Average total (f,p,t) tie voting intent",
    div.comp.pol. = "Diversity variables: PCA 1st component",
    div.comp.fr. = "Diversity variables: PCA 1st component"
  )
  vn <- c(vn1, vn2, vn2, vn2)
  names(vn) <- c(names(vn1),
    paste0(names(vn2), "in"),
    paste0(names(vn2), "out"),
    paste0(names(vn2), "both"))
  bin_versions <- paste0(vn[grep(".both$", names(vn))], " (Median split)")
  names(bin_versions) <- paste0(grep(".both$", names(vn), value = TRUE), ".bin")
  vn <- c(vn, bin_versions)
  vn[vars]
}
